version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 52795:52773
      - 53773
    volumes:
      - ./:/irisdev/app

  initiator:
    build:
      context: .
      dockerfile: ./acceptor/Dockerfile
    restart: always
    working_dir: ${WORKING_DIR}
    volumes:
      - ./:${WORKING_DIR}
    command:
      - ${WORKING_DIR}/initiator/start.sh
    stdin_open: true
    tty: true
    env_file:
      - .env